package knowledge

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"
)

const (
	inceptionStateFile  = "inception/state.json"
	ideaDefaultConf     = 0.3
	visionDefaultConf   = 0.6
	constDefaultConf    = 0.9
	reqDefaultConf      = 0.6
	constraintDefaultConf = 0.7
	stakeholderDefaultConf = 0.7
	acceptanceDefaultConf  = 0.6
	brownfieldConfBoost = 0.15
)

// InceptionEngine manages the Level 1 ideation workflow — from raw idea to
// structured KB facts and scaffold output. Supports both greenfield (new
// project) and brownfield (existing repo) modes.
type InceptionEngine struct {
	dataDir string
	api     *KnowledgeAPI
	mu      sync.Mutex
	state   *InceptionState
	logger  *slog.Logger
}

// NewInceptionEngine creates an engine that persists state under dataDir.
func NewInceptionEngine(dataDir string, api *KnowledgeAPI, logger *slog.Logger) *InceptionEngine {
	e := &InceptionEngine{
		dataDir: dataDir,
		api:     api,
		logger:  logger,
	}
	e.loadState()
	e.connectExistingVault()
	return e
}

// Start begins a greenfield inception — the user has an idea but no repo.
func (e *InceptionEngine) Start(rawIdea string) (*InceptionState, error) {
	e.mu.Lock()
	defer e.mu.Unlock()

	if rawIdea == "" {
		return nil, fmt.Errorf("idea text is required")
	}

	slug := slugify("idea-" + truncateSlug(rawIdea))

	if e.api != nil {
		ctx := context.Background()
		err := e.api.CreateFact(ctx, CreateFactRequest{
			Title:      rawIdea,
			Body:       rawIdea,
			Type:       string(FactIdea),
			Tags:       []string{"inception", "seed"},
			Layer:      string(LayerProject),
			Confidence: ideaDefaultConf,
		})
		if err != nil {
			e.logger.Warn("could not persist idea fact to KB layer (knowledge may not be configured)", "error", err)
		}
	}

	e.state = &InceptionState{
		Phase:     PhaseCapture,
		Mode:      InceptionGreenfield,
		IdeaText:  rawIdea,
		IdeaSlug:  slug,
		FactSlugs: []string{slug},
		Answers:   make(map[string]string),
		StartedAt: time.Now(),
	}

	if err := e.saveState(); err != nil {
		return nil, fmt.Errorf("persisting state: %w", err)
	}

	e.logger.Info("inception started",
		"mode", "greenfield",
		"slug", slug,
	)

	return e.state, nil
}

// StartBrownfield begins an inception against an existing repo. The guide
// agent will scan the repo and extract initial facts.
func (e *InceptionEngine) StartBrownfield(repoURL string) (*InceptionState, error) {
	e.mu.Lock()
	defer e.mu.Unlock()

	if repoURL == "" {
		return nil, fmt.Errorf("repo URL is required")
	}

	slug := slugify("scan-" + repoBaseName(repoURL))

	e.state = &InceptionState{
		Phase:     PhaseCapture,
		Mode:      InceptionBrownfield,
		IdeaSlug:  slug,
		RepoURL:   repoURL,
		FactSlugs: []string{},
		Answers:   make(map[string]string),
		StartedAt: time.Now(),
	}

	if err := e.saveState(); err != nil {
		return nil, fmt.Errorf("persisting state: %w", err)
	}

	e.logger.Info("inception started",
		"mode", "brownfield",
		"repo", repoURL,
		"slug", slug,
	)

	return e.state, nil
}

// SetQuestions records the clarification questions generated by the guide agent
// and advances the state to the clarify phase.
func (e *InceptionEngine) SetQuestions(questions []Question) error {
	e.mu.Lock()
	defer e.mu.Unlock()

	if e.state == nil {
		return fmt.Errorf("no inception in progress")
	}

	e.state.Questions = questions
	e.state.Phase = PhaseClarify

	return e.saveState()
}

// SubmitAnswers records user responses to clarification questions and advances
// to the structure phase. The scheduler will re-kick the guide agent with
// the answers injected.
func (e *InceptionEngine) SubmitAnswers(answers map[string]string) (*InceptionState, error) {
	e.mu.Lock()
	defer e.mu.Unlock()

	if e.state == nil {
		return nil, fmt.Errorf("no inception in progress")
	}
	// Accept answers in clarify or structure phase — the brainstorm agent
	// can advance past clarify before the user submits, but the answers
	// are still valuable context for the next kick.
	if e.state.Phase != PhaseClarify && e.state.Phase != PhaseStructure {
		return nil, fmt.Errorf("cannot submit answers in phase %s", e.state.Phase)
	}

	e.state.Answers = answers
	if e.state.Phase == PhaseClarify {
		e.state.Phase = PhaseStructure
	}

	if err := e.saveState(); err != nil {
		return nil, fmt.Errorf("persisting state: %w", err)
	}

	e.logger.Info("inception answers submitted",
		"answer_count", len(answers),
		"mode", e.state.Mode,
	)

	return e.state, nil
}

// RecordFacts records structured facts produced by the guide agent during the
// structure phase. Each fact is ingested into the project KB layer.
func (e *InceptionEngine) RecordFacts(ctx context.Context, facts []IdeationFact) error {
	e.mu.Lock()
	defer e.mu.Unlock()

	if e.state == nil {
		return fmt.Errorf("no inception in progress")
	}

	for _, f := range facts {
		conf := defaultConfidence(f.Type)
		if e.state.Mode == InceptionBrownfield {
			conf += brownfieldConfBoost
			if conf > 1.0 {
				conf = 1.0
			}
		}

		if e.api == nil {
			slug := slugify(string(f.Type) + "-" + truncateSlug(f.Title))
			e.state.FactSlugs = append(e.state.FactSlugs, slug)
			continue
		}

		err := e.api.CreateFact(ctx, CreateFactRequest{
			Title:      f.Title,
			Body:       f.Body,
			Type:       string(f.Type),
			Tags:       append(f.Tags, "inception"),
			Layer:      string(LayerProject),
			Confidence: conf,
		})
		if err != nil {
			e.logger.Warn("failed to record ideation fact",
				"title", f.Title,
				"type", f.Type,
				"error", err,
			)
			continue
		}

		slug := slugify(string(f.Type) + "-" + truncateSlug(f.Title))
		e.state.FactSlugs = append(e.state.FactSlugs, slug)
	}

	e.state.Phase = PhaseScaffold

	e.writeFactsToVault(facts)

	return e.saveState()
}

const inceptionVaultDir = "inception-kb"

// writeFactsToVault writes each fact as a markdown file with YAML frontmatter
// into a local directory, then connects it as a KB vault so facts are available
// to all agents via ${KNOWLEDGE} priming.
func (e *InceptionEngine) writeFactsToVault(facts []IdeationFact) {
	vaultDir := filepath.Join(e.dataDir, inceptionVaultDir)
	if err := os.MkdirAll(vaultDir, 0o755); err != nil {
		e.logger.Warn("failed to create inception vault dir", "error", err)
		return
	}

	for _, f := range facts {
		slug := slugify(string(f.Type) + "-" + truncateSlug(f.Title))
		filename := slug + ".md"

		conf := defaultConfidence(f.Type)
		tags := append(f.Tags, "inception", string(f.Type))

		var content strings.Builder
		content.WriteString("---\n")
		fmt.Fprintf(&content, "title: %s\n", f.Title)
		fmt.Fprintf(&content, "type: %s\n", string(f.Type))
		fmt.Fprintf(&content, "confidence: %.2f\n", conf)
		if len(tags) > 0 {
			fmt.Fprintf(&content, "tags: [%s]\n", strings.Join(tags, ", "))
		}
		content.WriteString("---\n\n")
		content.WriteString(f.Body)

		path := filepath.Join(vaultDir, filename)
		if err := os.WriteFile(path, []byte(content.String()), 0o644); err != nil {
			e.logger.Warn("failed to write inception fact file", "path", path, "error", err)
			continue
		}
	}

	if e.api != nil {
		if err := e.api.ConnectVault(vaultDir, "inception"); err != nil {
			if !strings.Contains(err.Error(), "already connected") {
				e.logger.Warn("failed to connect inception vault", "error", err)
			}
		} else {
			e.logger.Info("inception vault connected as knowledge source",
				"dir", vaultDir,
				"facts", len(facts),
			)
		}
	}
}

// connectExistingVault checks if inception facts were previously written to disk
// and reconnects the vault on startup (survives container restarts).
func (e *InceptionEngine) connectExistingVault() {
	if e.api == nil {
		return
	}
	vaultDir := filepath.Join(e.dataDir, inceptionVaultDir)
	entries, err := os.ReadDir(vaultDir)
	if err != nil || len(entries) == 0 {
		return
	}
	if err := e.api.ConnectVault(vaultDir, "inception"); err != nil {
		if !strings.Contains(err.Error(), "already connected") {
			e.logger.Warn("failed to reconnect inception vault on startup", "error", err)
		}
	} else {
		e.logger.Info("inception vault reconnected on startup",
			"dir", vaultDir,
			"files", len(entries),
		)
	}
}

// IdeationFact is the input for recording a new ideation fact from the guide agent.
type IdeationFact struct {
	Title string   `json:"title"`
	Body  string   `json:"body"`
	Type  FactType `json:"type"`
	Tags  []string `json:"tags"`
}

// ProduceScaffold generates bootstrap files from the structured facts. For
// greenfield, this is a full project skeleton. For brownfield, only missing
// files are generated.
func (e *InceptionEngine) ProduceScaffold(ctx context.Context) (*ScaffoldResult, error) {
	e.mu.Lock()
	defer e.mu.Unlock()

	if e.state == nil {
		return nil, fmt.Errorf("no inception in progress")
	}

	facts := e.gatherFacts(ctx)

	result := &ScaffoldResult{}

	vision := findFactByType(facts, FactVision)
	constitution := findFactByType(facts, FactConstitution)
	requirements := filterFactsByType(facts, FactRequirement)
	constraints := filterFactsByType(facts, FactConstraint)
	acceptance := filterFactsByType(facts, FactAcceptance)
	stakeholders := filterFactsByType(facts, FactStakeholder)

	result.Files = append(result.Files, ScaffoldFile{
		Path:    "README.md",
		Content: buildReadme(vision, requirements, constraints, stakeholders),
		Purpose: "readme",
		IsNew:   true,
	})

	result.Files = append(result.Files, ScaffoldFile{
		Path:    "CLAUDE.md",
		Content: buildClaudeMD(constitution, constraints),
		Purpose: "claude_md",
		IsNew:   true,
	})

	if len(acceptance) > 0 {
		result.Files = append(result.Files, ScaffoldFile{
			Path:    inferTestPath(constitution),
			Content: buildTestStubs(acceptance, constitution),
			Purpose: "test_stub",
			IsNew:   true,
		})
	}

	result.Files = append(result.Files, ScaffoldFile{
		Path:    "CONTRIBUTING.md",
		Content: buildContributing(constitution),
		Purpose: "contributing",
		IsNew:   true,
	})

	result.Files = append(result.Files, ScaffoldFile{
		Path:    ".github/workflows/ci.yml",
		Content: buildCIConfig(constitution),
		Purpose: "ci",
		IsNew:   true,
	})

	return result, nil
}

// AdvanceToComplete marks the inception as complete (scaffold approved).
func (e *InceptionEngine) AdvanceToComplete() error {
	e.mu.Lock()
	defer e.mu.Unlock()

	if e.state == nil {
		return fmt.Errorf("no inception in progress")
	}

	e.state.Phase = PhaseComplete
	e.logger.Info("inception complete",
		"mode", e.state.Mode,
		"facts", len(e.state.FactSlugs),
	)
	return e.saveState()
}

// GetState returns the current inception state, or nil if none is in progress.
func (e *InceptionEngine) GetState() *InceptionState {
	e.mu.Lock()
	defer e.mu.Unlock()
	return e.state
}

// ReadIdeaFact returns the seed idea fact for the current inception.
func (e *InceptionEngine) ReadIdeaFact(ctx context.Context) (*Fact, error) {
	e.mu.Lock()
	defer e.mu.Unlock()

	if e.state == nil {
		return nil, fmt.Errorf("no inception in progress")
	}
	if e.api == nil {
		return nil, nil
	}
	return e.api.ReadFact(ctx, e.state.IdeaSlug)
}

// Reset clears the inception state so the user can start over.
func (e *InceptionEngine) Reset() error {
	e.mu.Lock()
	defer e.mu.Unlock()

	e.state = nil
	path := filepath.Join(e.dataDir, inceptionStateFile)
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("removing state file: %w", err)
	}

	e.logger.Info("inception reset")
	return nil
}

// FormatAnswersForPrompt renders user answers as markdown for injection into
// the guide agent's kick template via ${INCEPTION_ANSWERS}.
func (e *InceptionEngine) FormatAnswersForPrompt() string {
	e.mu.Lock()
	defer e.mu.Unlock()

	if e.state == nil || len(e.state.Answers) == 0 {
		return ""
	}

	var b strings.Builder
	b.WriteString("# User Answers\n\n")
	for _, q := range e.state.Questions {
		answer, ok := e.state.Answers[q.ID]
		if !ok {
			continue
		}
		fmt.Fprintf(&b, "**%s**\n%s\n\n", q.Text, answer)
	}
	return b.String()
}

// --- persistence ---

func (e *InceptionEngine) loadState() {
	path := filepath.Join(e.dataDir, inceptionStateFile)
	data, err := os.ReadFile(path)
	if err != nil {
		return
	}
	var state InceptionState
	if err := json.Unmarshal(data, &state); err != nil {
		e.logger.Warn("corrupt inception state", "path", path, "error", err)
		return
	}
	e.state = &state
	e.logger.Info("inception state loaded",
		"phase", state.Phase,
		"mode", state.Mode,
	)
}

func (e *InceptionEngine) saveState() error {
	path := filepath.Join(e.dataDir, inceptionStateFile)
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("creating state dir: %w", err)
	}

	data, err := json.MarshalIndent(e.state, "", "  ")
	if err != nil {
		return fmt.Errorf("marshaling state: %w", err)
	}

	return os.WriteFile(path, data, 0o644)
}

// --- fact helpers ---

func (e *InceptionEngine) gatherFacts(ctx context.Context) []Fact {
	if e.api == nil {
		return nil
	}
	return e.api.LayerFacts(ctx, LayerProject, "")
}

func findFactByType(facts []Fact, ft FactType) *Fact {
	for _, f := range facts {
		if f.Type == ft {
			return &f
		}
	}
	return nil
}

func filterFactsByType(facts []Fact, ft FactType) []Fact {
	var result []Fact
	for _, f := range facts {
		if f.Type == ft {
			result = append(result, f)
		}
	}
	return result
}

func defaultConfidence(ft FactType) float64 {
	switch ft {
	case FactIdea:
		return ideaDefaultConf
	case FactVision:
		return visionDefaultConf
	case FactConstitution:
		return constDefaultConf
	case FactRequirement:
		return reqDefaultConf
	case FactConstraint:
		return constraintDefaultConf
	case FactStakeholder:
		return stakeholderDefaultConf
	case FactAcceptance:
		return acceptanceDefaultConf
	default:
		return 0.5
	}
}

// --- scaffold builders ---

func buildReadme(vision *Fact, reqs, constraints, stakeholders []Fact) string {
	var b strings.Builder

	title := "Project"
	if vision != nil {
		title = vision.Title
	}

	fmt.Fprintf(&b, "# %s\n\n", title)

	if vision != nil {
		b.WriteString(vision.Body)
		b.WriteString("\n\n")
	}

	if len(stakeholders) > 0 {
		b.WriteString("## Who Is This For\n\n")
		for _, s := range stakeholders {
			fmt.Fprintf(&b, "- **%s** — %s\n", s.Title, s.Body)
		}
		b.WriteString("\n")
	}

	if len(reqs) > 0 {
		b.WriteString("## Features\n\n")
		for _, r := range reqs {
			fmt.Fprintf(&b, "- %s\n", r.Title)
		}
		b.WriteString("\n")
	}

	if len(constraints) > 0 {
		b.WriteString("## Constraints\n\n")
		for _, c := range constraints {
			fmt.Fprintf(&b, "- %s\n", c.Title)
		}
		b.WriteString("\n")
	}

	b.WriteString("## Getting Started\n\n")
	b.WriteString("TODO: Add setup instructions.\n\n")

	b.WriteString("## License\n\n")
	b.WriteString("TODO: Choose a license.\n")

	return b.String()
}

func buildClaudeMD(constitution *Fact, constraints []Fact) string {
	var b strings.Builder

	b.WriteString("# Project Guidelines\n\n")

	if constitution != nil {
		b.WriteString("## Principles\n\n")
		b.WriteString(constitution.Body)
		b.WriteString("\n\n")
	}

	if len(constraints) > 0 {
		b.WriteString("## Constraints\n\n")
		for _, c := range constraints {
			fmt.Fprintf(&b, "- %s\n", c.Title)
		}
		b.WriteString("\n")
	}

	b.WriteString("## Code Quality\n\n")
	b.WriteString("- No magic numbers — use named constants\n")
	b.WriteString("- All commits must be signed with DCO\n")
	b.WriteString("- Run tests before committing\n")

	return b.String()
}

func buildTestStubs(acceptance []Fact, constitution *Fact) string {
	lang := inferLanguage(constitution)

	switch lang {
	case "go":
		return buildGoTestStubs(acceptance)
	case "typescript", "javascript":
		return buildTSTestStubs(acceptance)
	case "python":
		return buildPythonTestStubs(acceptance)
	default:
		return buildGoTestStubs(acceptance)
	}
}

func buildGoTestStubs(acceptance []Fact) string {
	var b strings.Builder
	b.WriteString("package main\n\nimport \"testing\"\n\n")
	for _, a := range acceptance {
		funcName := "Test" + toPascalCase(a.Title)
		fmt.Fprintf(&b, "func %s(t *testing.T) {\n", funcName)
		fmt.Fprintf(&b, "\tt.Skip(\"TODO: %s\")\n", a.Title)
		b.WriteString("}\n\n")
	}
	return b.String()
}

func buildTSTestStubs(acceptance []Fact) string {
	var b strings.Builder
	b.WriteString("import { describe, it } from 'vitest';\n\n")
	b.WriteString("describe('acceptance criteria', () => {\n")
	for _, a := range acceptance {
		fmt.Fprintf(&b, "  it.todo('%s');\n", strings.ReplaceAll(a.Title, "'", "\\'"))
	}
	b.WriteString("});\n")
	return b.String()
}

func buildPythonTestStubs(acceptance []Fact) string {
	var b strings.Builder
	b.WriteString("import pytest\n\n")
	for _, a := range acceptance {
		funcName := "test_" + toSnakeCase(a.Title)
		fmt.Fprintf(&b, "@pytest.mark.skip(reason=\"TODO: %s\")\n", a.Title)
		fmt.Fprintf(&b, "def %s():\n    pass\n\n", funcName)
	}
	return b.String()
}

func buildContributing(constitution *Fact) string {
	var b strings.Builder
	b.WriteString("# Contributing\n\n")
	b.WriteString("Thank you for your interest in contributing!\n\n")
	b.WriteString("## Development Setup\n\n")
	b.WriteString("TODO: Add development setup instructions.\n\n")
	b.WriteString("## Pull Request Process\n\n")
	b.WriteString("1. Fork the repository and create your branch from `main`\n")
	b.WriteString("2. Ensure tests pass before submitting\n")
	b.WriteString("3. Sign all commits with DCO (`git commit -s`)\n")
	b.WriteString("4. Open a PR with a clear description of the change\n\n")

	if constitution != nil {
		b.WriteString("## Code Style\n\n")
		b.WriteString(constitution.Body)
		b.WriteString("\n")
	}

	return b.String()
}

func buildCIConfig(constitution *Fact) string {
	lang := inferLanguage(constitution)

	switch lang {
	case "go":
		return goCI()
	case "typescript", "javascript":
		return tsCI()
	case "python":
		return pythonCI()
	default:
		return goCI()
	}
}

func goCI() string {
	return `name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - run: go build ./...
      - run: go test ./...
      - run: go vet ./...
`
}

func tsCI() string {
	return `name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm run build
      - run: npm run lint
      - run: npm test
`
}

func pythonCI() string {
	return `name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -e ".[dev]"
      - run: pytest
`
}

// --- string helpers ---

func slugify(s string) string {
	s = strings.ToLower(s)
	s = strings.Map(func(r rune) rune {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '-' {
			return r
		}
		if r == ' ' || r == '_' {
			return '-'
		}
		return -1
	}, s)
	for strings.Contains(s, "--") {
		s = strings.ReplaceAll(s, "--", "-")
	}
	return strings.Trim(s, "-")
}

func truncateSlug(s string) string {
	const maxSlugInputLen = 60
	if len(s) > maxSlugInputLen {
		s = s[:maxSlugInputLen]
	}
	return s
}

func repoBaseName(url string) string {
	url = strings.TrimSuffix(url, ".git")
	parts := strings.Split(url, "/")
	if len(parts) == 0 {
		return "repo"
	}
	return parts[len(parts)-1]
}

func inferLanguage(constitution *Fact) string {
	if constitution == nil {
		return "go"
	}
	body := strings.ToLower(constitution.Body)
	switch {
	case strings.Contains(body, "typescript") || strings.Contains(body, "react") || strings.Contains(body, "node"):
		return "typescript"
	case strings.Contains(body, "python") || strings.Contains(body, "pytest") || strings.Contains(body, "pip"):
		return "python"
	case strings.Contains(body, "javascript") || strings.Contains(body, "vitest"):
		return "javascript"
	default:
		return "go"
	}
}

func inferTestPath(constitution *Fact) string {
	lang := inferLanguage(constitution)
	switch lang {
	case "go":
		return "main_test.go"
	case "typescript", "javascript":
		return "src/__tests__/acceptance.test.ts"
	case "python":
		return "tests/test_acceptance.py"
	default:
		return "main_test.go"
	}
}

func toPascalCase(s string) string {
	words := strings.Fields(s)
	var b strings.Builder
	for _, w := range words {
		w = strings.Map(func(r rune) rune {
			if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
				return r
			}
			return -1
		}, w)
		if w == "" {
			continue
		}
		b.WriteString(strings.ToUpper(w[:1]) + w[1:])
	}
	return b.String()
}

func toSnakeCase(s string) string {
	words := strings.Fields(strings.ToLower(s))
	var filtered []string
	for _, w := range words {
		w = strings.Map(func(r rune) rune {
			if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '_' {
				return r
			}
			return -1
		}, w)
		if w != "" {
			filtered = append(filtered, w)
		}
	}
	return strings.Join(filtered, "_")
}
